branches:
  only:
    - master
    - joseph
    - tom
dist: xenial
language: python
python:
  - "3.7"
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda config --append channels conda-forge --append channels omnia 
  - conda info -a
  - conda create -q -n test-env python=$TRAVIS_PYTHON_VERSION --file requirements.txt
  - source activate test-env
  - python setup.py install
jobs:
  include:
    - stage: test
      name: Run unit tests
      script:
        - py.test --cov-report term --cov autode tests/
      after_success:
        - codecov
    - stage: deploy
      name: Deploy to GitHub Pages 
      script:
        - pip install -r doc/requirements.txt
        - cd doc
        - make html
        - touch _build/html/.nojekyll 
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $token
        local_dir: doc/_build/html
        on:
          branch: master